name = "Arcrepitus"
author = "AIGO Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7103346db813b9334d943b252f14735160564090ef16289fa6db2da5317929b"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
