name = "Arcrepitus"
author = "AIGO Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48c4ca2ba4c84ab06bd2a5f523746bfbcba62eebd1e8797f591af149b6082b80"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
