name = "Arcrepitus"
author = "AIGO Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ff1668e3b0c1f961cb46aeaab44472bcaa5bf36d78437565a3f2e9dd43413c6"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
